# Header
menu:
  主页: /
  归档: /archives/
  javascript: /categories/javascript/
  html/html5: /categories/html-html5/
  css/css3: /categories/css-css3/
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
# - tenfour
- category
# - tag
- archive
- tagcloud
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: