# Header
menu:
  主页: /
  # 归档: /archives/
  前端综合: /categories/前端综合/
  javascript: /categories/javascript/
  html/html5: /categories/html-html5/
  css/css3: /categories/css-css3/
rss: /atom.xml

# Search
search: true

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar 侧边栏
sidebar: right
widgets:
- tenfour
- category
# - tag
- tagcloud
- archive
# - recent_posts
- links

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# links 友情链接
links:
  丫丫加油: http://www.yaya12.com

# power by 免费赞助
powerby:
  qiniu:
    name: 七牛存储
    src: http://www.qiniu.com/
    imgurl: http://7xj45h.com1.z0.glb.clouddn.com/blogqiniu.png
  changyan:
    name: 畅言评论
    src: http://changyan.kuaizhan.com/
    imgurl: http://7xj45h.com1.z0.glb.clouddn.com/blogchangyan.png
  github:
    name: GitHub
    src: https://github.com/
    imgurl: http://7xj45h.com1.z0.glb.clouddn.com/bloggithub.png
  swiftype:
    name: Swiftype
    src: https://swiftype.com/
    imgurl: http://7xj45h.com1.z0.glb.clouddn.com/blogswitype.png